######################################################
# 1 - IMAGE ESSENTIELLE - Installation des dépendances système et PHP
######################################################
FROM php:8.3-apache AS essential

# Installe les dépendances système et PHP nécessaires
RUN apt-get update && apt-get install -y \
    unzip \
    zip \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    libicu-dev \
    libpng-dev \
    libjpeg-dev \
    libwebp-dev \
    libfreetype6-dev \
    zlib1g-dev \
    build-essential \
    curl \
    g++ \
    && docker-php-ext-install pdo pdo_mysql intl opcache zip bcmath \
    && pecl install apcu \
    && docker-php-ext-enable apcu

# Active les modules Apache utiles pour Symfony
RUN a2enmod rewrite ssl socache_shmcb

# Copie la configuration Apache
COPY ./apache/default.conf /etc/apache2/sites-available/000-default.conf

######################################################
# 2 - BUILD IMAGE - Installer les dépendances et compiler les assets
######################################################
FROM essential AS build

WORKDIR /app

ENV APP_ENV=prod
ENV DEBUG=0

# Copier Composer depuis l'image officielle
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Copier tout le projet
COPY . .

# Installer toutes les dépendances, y compris dev pour builder correctement
RUN composer install --no-interaction --optimize-autoloader

# Compiler les assets et importmap
RUN php bin/console importmap:install --env=prod -n
RUN php bin/console sass:build --env=prod
RUN php bin/console asset-map:compile --env=prod

# Nettoyer et préchauffer le cache
RUN php bin/console cache:clear
RUN php bin/console cache:warmup

######################################################
# 3 - BUILD NODE POUR LES ASSETS JS
######################################################
FROM node:25.1.0-alpine3.22 AS build-node

WORKDIR /app
COPY --from=build /app /app

RUN npm ci
RUN npm run build

######################################################
# 4 - IMAGE FINALE PROD LÉGÈRE
######################################################
FROM php:8.3-apache AS prod

WORKDIR /var/www

# Installer les extensions PHP de base et bcmath pour prod
RUN apt-get update && apt-get install -y \
    libonig-dev libxml2-dev libzip-dev libicu-dev libpng-dev libjpeg-dev libwebp-dev libfreetype6-dev zlib1g-dev \
    && docker-php-ext-install pdo pdo_mysql intl opcache zip bcmath \
    && pecl install apcu \
    && docker-php-ext-enable apcu \
    && a2enmod rewrite ssl socache_shmcb

# Copier l'application buildée
COPY --from=build-node /app /var/www/

# Créer les dossiers cache/log et permissions
RUN mkdir -p var/cache var/log \
    && chown -R www-data:www-data /var/www \
    && chmod -R 775 var
